# Generated by Django 4.1 on 2022-10-18 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('ordered_product', models.CharField(max_length=100, verbose_name='Наименование')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='store_app.order', verbose_name='Данные заказчика')),
            ],
        ),
    ]
